import { useEffect, useMemo, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import {
  Bot,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  KeyRound,
  Send,
  Settings2,
  Volume2,
  X,
} from "lucide-react";
import {
  askTutor,
  loadSettings,
  saveSettings,
  PROVIDERS,
  PROVIDER_LIST,
  type ChatMessage,
  type ProviderId,
  type TutorSettings,
} from "@/lib/tutor/byok";
import { checkReply } from "@/lib/tutor/guard";
import { dispatchTutorActions, parseTutorActions } from "@/lib/tutor/actions";
import { Storage } from "@/lib/storage";

const GREETING =
  "I'm Socratic, your lab tutor. I can see your canvas, your examples and your last mistake — but I'll never hand you the fix. Ask me anything, or say **\"hint\"**.";

/** Strip the model's private reasoning block from any text that leaves the panel. */
export function stripThink(text: string): string {
  return text.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
}

function splitThink(text: string): { think: string | null; body: string } {
  const m = text.match(/<think>([\s\S]*?)<\/think>/i);
  return { think: m?.[1]?.trim() || null, body: stripThink(text) };
}

function speak(text: string) {
  if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
  const utter = new SpeechSynthesisUtterance(text);
  utter.rate = 1;
  window.speechSynthesis.cancel();
  window.speechSynthesis.speak(utter);
}

/**
 * Cross-session recall, grounded in persisted app performance data (never in
 * chat content). Aggregate stats the student generated by using the app.
 */
function recallOpener(): string | null {
  const top = Storage.getMistakeSummary().data[0];
  const solved = Storage.countSolvedUnique();
  const attempted = Storage.countAttemptedUnique();
  if (top && top.count >= 2)
    return `Picking up where you left off: **${top.category}** has tripped you up ${top.count} times. Want a quick drill aimed at exactly that?`;
  if (attempted >= 3)
    return `You've attempted ${attempted} challenges and solved ${solved}. Want to push into a harder one?`;
  return null;
}

/**
 * Rolling summarization: instead of hard-truncating a long thread, fold the
 * oldest ~30% of turns into one short pseudo-message. Purely local — no network.
 */
const KEEP_TURNS = 14;
function compactHistory(history: ChatMessage[]): ChatMessage[] {
  if (history.length <= KEEP_TURNS) return history;
  const cut = Math.max(1, Math.floor(history.length * 0.3));
  const old = history.slice(0, cut);
  const rest = history.slice(cut);
  const asked = old.filter((m) => m.role === "user").map((m) => stripThink(m.content).slice(0, 90));
  const summary: ChatMessage = {
    role: "user",
    content: `[earlier in this session, summarized] The student asked about: ${asked.join(" | ") || "general concepts"}. Continue without repeating those explanations verbatim.`,
  };
  return [summary, ...rest];
}

interface Sketch {
  title: string;
  states: string[];
  edges: { from: number; to: number; label: string }[];
}

/** Generic illustrative sketch — dummy names only, never the student's machine. */
function parseSketch(spec: string, title: string): Sketch | null {
  const edges: Sketch["edges"] = [];
  const names: string[] = [];
  const idx = (n: string) => {
    const at = names.indexOf(n);
    if (at >= 0) return at;
    names.push(n);
    return names.length - 1;
  };
  for (const part of spec.split(";")) {
    const m = part.trim().match(/^([\w']+)\s*-\s*([^->]*)\s*->\s*([\w']+)$/);
    if (!m) continue;
    edges.push({ from: idx(m[1]!), to: idx(m[3]!), label: (m[2] || "").trim() || "·" });
  }
  if (!edges.length) return null;
  return { title, states: names, edges };
}

function ScratchDiagram({ sketch, onClear }: { sketch: Sketch; onClear: () => void }) {
  const positions = sketch.states.map((_, i) => ({ x: 46 + i * 88, y: 52 }));
  return (
    <div className="lab-card" style={{ margin: "0 10px 8px" }}>
      <div className="flex items-center gap-2">
        <p className="section-label" style={{ margin: 0 }}>
          Scratch sketch — generic example
        </p>
        <button className="tool-btn ml-auto" title="Clear sketch" onClick={onClear}>
          <X size={13} />
        </button>
      </div>
      <p className="text-[11px]" style={{ color: "var(--ink-muted)" }}>
        {sketch.title}
      </p>
      <svg
        role="img"
        aria-label={`Illustrative diagram: ${sketch.title}`}
        width="100%"
        height={104}
        viewBox={`0 0 ${Math.max(220, 46 + sketch.states.length * 88)} 104`}
      >
        {sketch.edges.map((e, i) => {
          const a = positions[e.from]!;
          const b = positions[e.to]!;
          if (e.from === e.to)
            return (
              <g key={i}>
                <path
                  d={`M ${a.x - 10} ${a.y - 18} q 10 -22 20 0`}
                  fill="none"
                  stroke="currentColor"
                  strokeWidth={1.2}
                  opacity={0.55}
                />
                <text
                  x={a.x}
                  y={a.y - 30}
                  textAnchor="middle"
                  fontSize={10}
                  fill="currentColor"
                  opacity={0.8}
                >
                  {e.label}
                </text>
              </g>
            );
          return (
            <g key={i}>
              <line
                x1={a.x + 18}
                y1={a.y}
                x2={b.x - 18}
                y2={b.y}
                stroke="currentColor"
                strokeWidth={1.2}
                opacity={0.55}
              />
              <text
                x={(a.x + b.x) / 2}
                y={a.y - 8}
                textAnchor="middle"
                fontSize={10}
                fill="currentColor"
                opacity={0.8}
              >
                {e.label}
              </text>
            </g>
          );
        })}
        {sketch.states.map((s, i) => (
          <g key={s}>
            <circle
              cx={positions[i]!.x}
              cy={positions[i]!.y}
              r={17}
              fill="none"
              stroke="currentColor"
              strokeWidth={1.3}
              opacity={0.8}
            />
            <text
              x={positions[i]!.x}
              y={positions[i]!.y + 4}
              textAnchor="middle"
              fontSize={11}
              fill="currentColor"
            >
              {s}
            </text>
          </g>
        ))}
      </svg>
    </div>
  );
}

export function TutorPanel({
  open,
  onClose,
  moduleId,
  getContext,
}: {
  open: boolean;
  onClose: () => void;
  moduleId: string;
  getContext: () => string;
}) {
  const [settings, setSettings] = useState<TutorSettings>(() => loadSettings());
  const [showSettings, setShowSettings] = useState(false);
  const [showKey, setShowKey] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    { role: "assistant", content: GREETING },
  ]);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [chips, setChips] = useState<{ tab: string; label: string }[]>([]);
  const [sketch, setSketch] = useState<Sketch | null>(null);
  const scroller = useRef<HTMLDivElement | null>(null);
  const composer = useRef<HTMLInputElement | null>(null);
  /** Converter reveal tracking — feeds the sequencing guard. */
  const reveal = useRef<Record<string, boolean>>({});

  useEffect(() => {
    setSettings(loadSettings());
    const opener = recallOpener();
    if (opener)
      setMessages((m) => (m.length === 1 ? [...m, { role: "assistant", content: opener }] : m));
  }, []);

  useEffect(() => {
    const onReveal = (e: Event) => {
      const d = (e as CustomEvent).detail as { moduleId: string; finalVisible: boolean };
      if (d?.moduleId) reveal.current[d.moduleId] = d.finalVisible;
    };
    window.addEventListener("iale-reveal-state", onReveal);
    return () => window.removeEventListener("iale-reveal-state", onReveal);
  }, []);

  useEffect(() => {
    if (open) composer.current?.focus();
  }, [open, moduleId]);

  useEffect(() => {
    if (!settings.apiKey && open) setShowSettings(true);
  }, [settings.apiKey, open]);

  useEffect(() => {
    scroller.current?.scrollTo({ top: scroller.current.scrollHeight, behavior: "smooth" });
  }, [messages, busy]);

  const rendered = useMemo(
    () => messages.map((m) => ({ role: m.role, ...splitThink(m.content) })),
    [messages],
  );

  function patch(next: Partial<TutorSettings>) {
    const merged = { ...settings, ...next };
    if (next.provider && next.provider !== settings.provider)
      merged.model = PROVIDERS[next.provider].models[0] ?? merged.model;
    setSettings(merged);
    saveSettings(merged);
  }

  async function send() {
    const question = input.trim();
    if (!question || busy) return;
    const history = compactHistory([
      ...messages
        .filter((m) => m.content !== GREETING)
        .map((m) => ({ ...m, content: stripThink(m.content) })),
      { role: "user" as const, content: question },
    ]);
    setMessages((m) => [...m, { role: "user", content: question }]);
    setInput("");
    setBusy(true);
    setError(null);

    const res = await askTutor(settings, getContext().slice(0, 6000), history.slice(-24));
    setBusy(false);

    if (!res.ok) {
      setError(res.error);
      return;
    }
    const { cleanText, actions } = parseTutorActions(res.text);
    const verdict = checkReply(stripThink(cleanText), {
      moduleId,
      finalVisible: reveal.current[moduleId] ?? true,
    });
    const finalText = verdict.allowed ? cleanText : verdict.fallback;
    setMessages((m) => [...m, { role: "assistant", content: finalText }]);
    composer.current?.focus();
    if (!verdict.allowed) return;

    dispatchTutorActions(actions);
    for (const a of actions) {
      if (a.type === "linkConcept")
        setChips((c) =>
          [...c.filter((x) => x.tab !== a.tab), { tab: a.tab, label: a.label }].slice(-3),
        );
      if (a.type === "readAloud") speak(a.text);
      if (a.type === "sketch") setSketch(parseSketch(a.spec, a.title));
      if (a.type === "exportNotes")
        exportNotes([...messages, { role: "assistant", content: finalText }]);
    }
  }

  function exportNotes(thread: ChatMessage[]) {
    const body = thread
      .map((m) => `${m.role === "user" ? "You" : "Socratic"}: ${stripThink(m.content)}`)
      .join("\n\n");
    const url = URL.createObjectURL(
      new Blob([`IALE session notes — ${moduleId}\n\n${body}\n`], { type: "text/plain" }),
    );
    const a = document.createElement("a");
    a.href = url;
    a.download = `iale-session-${moduleId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (!open) return null;
  const provider = PROVIDERS[settings.provider];

  return (
    <aside className="tutor-panel">
      <header className="tutor-head">
        <Bot size={16} style={{ color: "var(--signal-blue)" }} />
        <span className="font-semibold text-sm">Socratic</span>
        <span className="badge" data-tone={settings.apiKey ? "accept" : "amber"}>
          {settings.apiKey ? provider.label.split(" ")[0] : "no key"}
        </span>
        <div className="ml-auto flex items-center gap-1">
          <button
            className="tool-btn"
            title="Read the last reply aloud"
            onClick={() => speak(stripThink(messages[messages.length - 1]?.content ?? ""))}
          >
            <Volume2 size={15} />
          </button>
          <button
            className="tool-btn"
            title="Download session notes"
            onClick={() => exportNotes(messages)}
          >
            <Download size={15} />
          </button>
          <button
            className="tool-btn"
            title="Tutor settings"
            onClick={() => setShowSettings((s) => !s)}
          >
            <Settings2 size={15} />
          </button>
          <button className="tool-btn" title="Close tutor" onClick={onClose}>
            <X size={15} />
          </button>
        </div>
      </header>

      {showSettings && (
        <div className="tutor-settings">
          <p className="section-label">Bring your own key</p>
          <p className="text-[11.5px] leading-relaxed" style={{ color: "var(--ink-muted)" }}>
            Your key is stored only in this browser and is sent directly to the provider. Nothing is
            proxied through this app, and no one else pays for your usage.
          </p>
          <label className="section-label">Provider</label>
          <select
            className="field-input"
            value={settings.provider}
            onChange={(e) => patch({ provider: e.target.value as ProviderId })}
          >
            {PROVIDER_LIST.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </select>
          <label className="section-label">Model</label>
          <select
            className="field-input"
            value={settings.model}
            onChange={(e) => patch({ model: e.target.value })}
          >
            {provider.models.map((m) => (
              <option key={m} value={m}>
                {m}
              </option>
            ))}
          </select>
          <label className="section-label">API key</label>
          <div className="flex gap-1">
            <input
              className="field-input"
              type={showKey ? "text" : "password"}
              autoComplete="off"
              spellCheck={false}
              placeholder={provider.keyPlaceholder}
              value={settings.apiKey}
              onChange={(e) => patch({ apiKey: e.target.value })}
            />
            <button
              className="tool-btn"
              title={showKey ? "Hide key" : "Show key"}
              onClick={() => setShowKey((s) => !s)}
            >
              {showKey ? <EyeOff size={15} /> : <Eye size={15} />}
            </button>
          </div>
          <a
            className="inline-flex items-center gap-1 text-[11.5px]"
            style={{ color: "var(--signal-blue)" }}
            href={provider.keysUrl}
            target="_blank"
            rel="noreferrer"
          >
            <KeyRound size={12} /> Get a {provider.label} key <ExternalLink size={11} />
          </a>
        </div>
      )}

      <div className="tutor-thread" ref={scroller}>
        {rendered.map((m, i) => (
          <div key={i} className="tutor-msg" data-role={m.role}>
            {m.think && (
              <details style={{ marginBottom: 6 }}>
                <summary
                  className="text-[11px] cursor-pointer"
                  style={{ color: "var(--ink-muted)" }}
                >
                  How I reasoned
                </summary>
                <div className="text-[11px] leading-relaxed" style={{ color: "var(--ink-muted)" }}>
                  {m.think}
                </div>
              </details>
            )}
            <div className="tutor-prose">
              <ReactMarkdown>{m.body}</ReactMarkdown>
            </div>
          </div>
        ))}
        {busy && (
          <div className="tutor-msg" data-role="assistant" style={{ color: "var(--ink-muted)" }}>
            Thinking…
          </div>
        )}
        {error && (
          <div className="tutor-msg" data-role="error">
            {error}
          </div>
        )}
      </div>

      {sketch && <ScratchDiagram sketch={sketch} onClear={() => setSketch(null)} />}

      {chips.length > 0 && (
        <div className="flex flex-wrap gap-1" style={{ padding: "0 10px 8px" }}>
          {chips.map((c) => (
            <button
              key={c.tab}
              className="chip"
              onClick={() => {
                window.dispatchEvent(
                  new CustomEvent("iale-tutor-action", { detail: { type: "gotoTab", tab: c.tab } }),
                );
                setChips((x) => x.filter((y) => y.tab !== c.tab));
              }}
            >
              {c.label}
            </button>
          ))}
        </div>
      )}

      <div className="tutor-compose">
        <input
          ref={composer}
          className="field-input"
          placeholder={settings.apiKey ? "Ask about your machine…" : "Add your API key to start"}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey) {
              e.preventDefault();
              void send();
            }
          }}
        />
        <button
          className="btn-primary"
          onClick={() => void send()}
          disabled={busy || !input.trim()}
          title="Send"
        >
          <Send size={14} />
        </button>
      </div>
    </aside>
  );
}
